### ISSUE TITLE
RFJAMMer script

### ISSUE THREAD

**Issue by alian2000** [AndrewMohawk/RfCatHelpers#2]
Andrew MacPherson,

I am trying to run the RFjammer python script within the rfcat ,not sure if i am doing it right but i am getting the following error,i am using ubuntu 17.04 and installed the rfcat successfully and i can listen to specific frequencies, Can you please help me on how to run the RFjammer script?

thanks

In [11]: sudo %%python ./RFjammer.py
  File "<ipython-input-11-d86edb8e1f20>", line 1
    sudo %%python ./RFjammer.py
          ^
SyntaxError: invalid syntax

In [12]: sudo %%python ./RFjammer.py
  File "<ipython-input-12-d86edb8e1f20>", line 1
    sudo %%python ./RFjammer.py
          ^
SyntaxError: invalid syntax

**Comment by vsboost** [comment]
Not sure what those %% are, is that what you are typing in at the terminal ?

should be ran like

python ./RFjammer.py

**Comment by AndrewMohawk** [comment]
Heya,

Yeah should just be able to run it like "python RFjammer.py" without any problems.

-AM

**Comment by doug79** [comment]
Hello I keep seeing no such file or directory.  I using ubuntu 16.04 also see the same in root can please help
